---

- name: Check that nginx is installed
  hosts: webservers
  remote_user: runner
  become: yes
  become_method: sudo

  tasks:
    - name: Check nginx is installed
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Check index exists with content
      ansible.builtin.copy:
        src: ./index.html
        dest: /var/www/html/index.nginx-debian.html
        owner: root
        group: root
        mode: '0666'
